# Generated by Django 5.0.6 on 2024-05-20 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: (999) 999-9999",
                        regex="^\\(\\d{3}) \\d{3}-\\d{4}$",
                    )
                ],
            ),
        ),
    ]
